name: PennyLane-Orquestra component tests
on:
  push:
    branches:
      - main
  pull_request:


env:
  COVERAGE_FLAGS: "--cov=steps --cov-report=term-missing --cov-report=xml --no-flaky-report -p no:warnings --tb=native"


jobs:
  core-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - {python-version: 3.9}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            orquestra:
              - pennylane_orquestra/**
              - tests/**
              - steps/**
              - src/**
              - .pylintrc
              - Makefile
              - MANIFEST.in
              - requirements.txt
              - setup.py

      - uses: actions/checkout@v2

      - name: Set up Python
        if: steps.filter.outputs.orquestra == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Install dependencies
        if: steps.filter.outputs.orquestra == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r steps/steps_requirements.txt
          pip install wheel pytest pytest-cov pytest-mock flaky --upgrade

      - name: Install PennyLane-Orquestra
        if: steps.filter.outputs.orquestra == 'true'
        run: |
          python setup.py bdist_wheel
          pip install dist/PennyLane_Orquestra*.whl

      - name: Run Forest Quilc
        if: steps.filter.outputs.orquestra == 'true'
        run: docker run --rm -d -p 5555:5555 rigetti/quilc -R

      - name: Run Forest QVM
        if: steps.filter.outputs.orquestra == 'true'
        run: docker run --rm -d -p 5000:5000 rigetti/qvm -S

      - name: Run tests
        if: steps.filter.outputs.orquestra == 'true'
        run: python -m pytest steps/test_* $COVERAGE_FLAGS

      - name: Upload coverage to Codecov
        if: steps.filter.outputs.orquestra == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
