name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:


env:
  COVERAGE_FLAGS: "--cov=pennylane_orquestra --cov-report=term-missing --cov-report=xml --no-flaky-report -p no:warnings --tb=native"


jobs:
  core-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - {python-version: 3.7}
          - {python-version: 3.8}
          - {python-version: 3.9}
          - {python-version: '3.10'}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel pytest pytest-cov pytest-mock flaky --upgrade

      - name: Install PennyLane-Orquestra
        run: |
          python setup.py bdist_wheel
          pip install dist/PennyLane_Orquestra*.whl

      - name: Run tests
        run: python -m pytest tests -k 'not e2e' $COVERAGE_FLAGS

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
